### ISSUE TITLE
Error: Cannot find module '../build/Release/bson

### ISSUE THREAD

**Issue by KingKush** [carlo-fontanos/node.js-e-commerce#1]
I ran npm install and then when I ran node server.js, I got the following error...
{ Error: Cannot find module '../build/Release/bson'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\xampp\htdocs\NodeComm\carlos\node_m
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3) code: 'MODULE_NOT_
js-bson: Failed to load c++ bson extension, using pure JS version

**Comment by KingKush** [comment]
My bad, found it.
